export const AUDITABLE_ORDER_BY = {
  CREATION_DATE_DESC: 'CREATION_DATE_DESC',
  CREATION_DATE_ASC: 'CREATION_DATE_ASC',
  MODIFIED_DATE_DESC: 'MODIFIED_DATE_DESC',
  MODIFIED_DATE_ASC: 'MODIFIED_DATE_ASC',
} as const;

export type AuditableOrderBy = (typeof AUDITABLE_ORDER_BY)[keyof typeof AUDITABLE_ORDER_BY];
